export enum ContentType {
  JSON = "application/json",
  XML = "application/xml",
  HTML = "text/html",
  PlainText = "text/plain",
  FormData = "multipart/form-data",
  URLFormEncoded = "application/x-www-form-urlencoded",
  OctetStream = "application/octet-stream",
  PDF = "application/pdf",
  JPEG = "image/jpeg",
  PNG = "image/png",
  GIF = "image/gif",
  SVG = "image/svg+xml",
  MP4 = "video/mp4",
  MP3 = "audio/mp3",
  CSV = "text/csv",
  Excel = "application/vnd.ms-excel",
  Word = "application/msword",
  PowerPoint = "application/vnd.ms-powerpoint",
  JavaScript = "application/javascript",
  CSS = "text/css",
}
